title: Westview Hotels Staff Guidelines
description: The staff guidelines for Westview Hotels and Resorts!
theme: just-the-docs

url: https://mattgamer6660.github.io/westviewhotelsSHR/
  
color_scheme: westview

callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue
logo: "logo.png"
favicon_ico: "favicon.ico"
